import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';

let app: FirebaseApp | undefined;
let auth: Auth | undefined;
let db: Firestore | undefined;
let isInitialized = false;

const loadFirebase = async () => {
  try {
    // @ts-ignore - this file is generated by set_up_firebase
    const config = await import('../../firebase-applet-config.json');
    if (config.default && Object.keys(config.default).length > 0) {
      if (!getApps().length) {
        app = initializeApp(config.default);
        auth = getAuth(app);
        db = getFirestore(app, (config.default as any).firestoreDatabaseId);
      } else {
        app = getApps()[0];
        auth = getAuth(app);
        db = getFirestore(app);
      }
    } else {
      console.warn('Firebase config is empty. Some features will be unavailable.');
    }
  } catch (error) {
    console.warn('Firebase config not found or invalid. Please ensure set_up_firebase was successful.', error);
  } finally {
    isInitialized = true;
  }
};

loadFirebase();

export { app, auth, db, isInitialized };

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  if (!auth) throw new Error('Firebase Auth not initialized');
  
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}
